### ISSUE TITLE
The select_prefixes function doesn't work corectly

### ISSUE THREAD

**Issue by AlDawoode** [mludvig/aws-ipranges-updater#1]
First, Thank You for sharing your project with us
I tried clone the project, but when i test it, i found that "selected prefixes function" in lambda doesn't work correctly.
if we define the select environment variable equals to 	
[{
		"region": "us-east-1",
		"services": [ "=AMAZON" ]
	}] 
we don't get any result "prefixes", my goal was to get all "Amazon related ip ranges FOR a spesific region".
I test it with diffenet values, but it doesn't work.

**Comment by mludvig** [comment]
Hi, thanks for the report. I believe it's now fixed in a139130. Cheers

**Comment by AlDawoode** [comment]
Now is working perfectly, Thank You
